version: '3'
services:
  nifi:
    image: apache/nifi:1.19.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=a1b2c3d4E%nifi
    volumes:
      - inputDir:/opt/nifi/nifi-current/input-directory

    restart: always

volumes:
  inputDir:
    # Define the host path to your local input directory here
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jeremy/Desktop/github/apache-nifi/inputDir
